name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 如果有 build 步驟，例如 Vite/React，放這裡
      #- name: Build
      #  run: npm install && npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./   # 改成 build 產出的資料夾，如果有

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
