name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 當 main 分支有 push 時自動觸發

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 如果有 build 步驟，例如 Vite/React，放這裡
      # - name: Build
      #   run: npm install && npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./   # 如果你的網站有 build 資料夾，改成 ./dist 或 ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
